apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 907322329163.dkr.ecr.ap-south-1.amazonaws.com/dockerrepo:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
